PREFIX was: <http://www.semanticweb.org/rubengonzalez/ontologies/2022/2/untitled-ontology-8#>
PREFIX schema: <http://schema.org/>

WITH <https://interactions.ics.unisg.ch/was-assignment-3-ruben#>
DELETE { 
        ?room a schema:Room.
        ?blind a was:Blind.
        ?blindState a was:BlindStateUp.
        ?lamp a was:Lamp.
        ?lampState a was:LampStateOn.
        ?goal a was:RoomDarker.
}
where {
        ?room a schema:Room.
        ?blind a was:Blind.
        ?blindState a was:BlindStateUp.
        ?lamp a was:Lamp.
        ?lampState a was:LampStateOn.
        ?goal a was:RoomDarker.
}